"""Driver protocols — defines interfaces for all automation drivers.

Five protocol families:
    DriverProtocol            — Desktop UI (pywinauto)
    WebDriverProtocol         — Web UI (Playwright)
    APIDriverProtocol         — REST API (httpx)
    DBDriverProtocol          — Database (psycopg2)
    SecurityScannerProtocol   — Security scanning (OWASP ZAP)

Usage::

    from ankole.driver.base import DriverProtocol, WebDriverProtocol, APIDriverProtocol
    from ankole.driver.base import DBDriverProtocol

    def my_helper(driver: WebDriverProtocol) -> None:
        driver.goto("https://example.com")
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DriverProtocol(Protocol):
    """Structural interface for desktop UI automation drivers (pywinauto)."""

    @property
    def main_window(self) -> Any: ...

    @property
    def app(self) -> Any: ...

    def start(self) -> DriverProtocol: ...
    def close(self) -> None: ...
    def refresh_window(self) -> Any: ...
    def set_retry_config(self, config: dict) -> None: ...
    def set_window_monitor(self, monitor: Any) -> None: ...

    def click_button(self, name: str | None = None, auto_id: str | None = None,
                     found_index: int = 0) -> None: ...
    def click_radio(self, auto_id: str | None = None, name: str | None = None,
                    found_index: int = 0) -> None: ...
    def click_element(self, **kwargs: Any) -> None: ...

    def type_text(self, text: str, auto_id: str | None = None,
                  name: str | None = None, **kwargs: Any) -> None: ...
    def type_keys_to_field(self, text: str, auto_id: str | None = None,
                           name: str | None = None, **kwargs: Any) -> None: ...
    def get_text(self, auto_id: str | None = None,
                 name: str | None = None, **kwargs: Any) -> str: ...

    def wait_for_element(self, timeout: int = 10, **kwargs: Any) -> Any: ...
    def element_exists(self, **kwargs: Any) -> bool: ...

    def select_combobox(self, name: str | None = None, auto_id: str | None = None,
                        value: str | None = None) -> None: ...
    def click_combobox_item(self, auto_id: str | None = None, name: str | None = None,
                            value: str | None = None) -> list[str]: ...
    def get_combobox_items(self, auto_id: str | None = None,
                           name: str | None = None) -> list[str]: ...
    def get_list_items(self, auto_id: str | None = None,
                       name: str | None = None) -> list[str]: ...
    def get_table_data(self, auto_id: str | None = None,
                       name: str | None = None) -> dict: ...

    def check_popup(self) -> Any: ...
    def dismiss_popup(self, button_name: str | None = None,
                      auto_id: str | None = None) -> bool: ...
    def dismiss_startup_popups(self) -> bool: ...

    def take_screenshot(self, name: str = "screenshot") -> Any: ...
    def print_control_tree(self, depth: int = 3) -> None: ...


@runtime_checkable
class WebDriverProtocol(Protocol):
    """Structural interface for web UI automation drivers (Playwright)."""

    def start(self, **kwargs: Any) -> WebDriverProtocol: ...
    def close(self) -> None: ...

    def goto(self, url: str) -> None: ...
    def click(self, selector: str) -> None: ...
    def fill(self, selector: str, value: str) -> None: ...
    def select_option(self, selector: str, value: str) -> None: ...
    def get_text(self, selector: str) -> str: ...
    def wait_for_selector(self, selector: str, timeout: float | None = None) -> Any: ...
    def take_screenshot(self, name: str = "screenshot") -> str: ...
    def get_table_data(self, selector: str) -> list[dict[str, str]]: ...

    def click_in_row(self, table_selector: str, row_text: str,
                     button_selector: str) -> None: ...
    def row_exists(self, table_selector: str, row_text: str) -> bool: ...
    def get_text_in_row(self, table_selector: str, row_text: str,
                        cell_selector: str) -> str: ...
    def get_all_elements_text(self, selector: str) -> list[str]: ...
    def get_elements_data(self, selector: str,
                          sub_selectors: dict[str, str]) -> list[dict[str, str]]: ...


@runtime_checkable
class APIDriverProtocol(Protocol):
    """Structural interface for REST API automation drivers (httpx)."""

    def login(self, username: str, password: str) -> Any: ...
    def logout(self) -> None: ...

    def get(self, path: str, **kwargs: Any) -> Any: ...
    def post(self, path: str, **kwargs: Any) -> Any: ...
    def put(self, path: str, **kwargs: Any) -> Any: ...
    def patch(self, path: str, **kwargs: Any) -> Any: ...
    def delete(self, path: str, **kwargs: Any) -> Any: ...


@runtime_checkable
class DBDriverProtocol(Protocol):
    """Structural interface for database drivers (psycopg2)."""

    def connect(self) -> "DBDriverProtocol": ...
    def close(self) -> None: ...
    def execute(self, query: str, params: tuple | None = None) -> Any: ...
    def execute_scalar(self, query: str, params: tuple | None = None) -> Any: ...
    def row_count(self, table: str, where: dict[str, Any] | None = None) -> int: ...
    def assert_row_exists(self, table: str, where: dict[str, Any]) -> Any: ...
    def assert_row_count(self, table: str, expected: int,
                         where: dict[str, Any] | None = None) -> Any: ...
    def assert_column_value(self, table: str, column: str, expected: Any,
                            where: dict[str, Any] | None = None) -> Any: ...


@runtime_checkable
class SecurityScannerProtocol(Protocol):
    """Structural interface for security scanning drivers (OWASP ZAP)."""

    def set_target(self, url: str) -> None: ...
    def run_spider(self, url: str, **kwargs: Any) -> Any: ...
    def run_passive_scan(self, **kwargs: Any) -> Any: ...
    def run_active_scan(self, url: str, **kwargs: Any) -> Any: ...
    def get_alerts(self, **kwargs: Any) -> list[Any]: ...
